@apimName = csaistoznvg3iu6nbs
@apiPath = Chickens

### Test APIM endpoint
GET https://{{apimName}}.azure-api.net/{{apiPath}}

### Example with specific values
# @apimName = mycompany-apim
# @apiPath = api/v1/chat
# GET https://{{apimName}}.azure-api.net/{{apiPath}}

# test comment